name: build and test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
    
      - name: Build with Maven
        run: mvn -B -s ./.m2/settings.xml -Pgitlab-cicd verify -Dspring.security.logging.requests=all --file pom.xml

  compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Advance Security Policy as Code
        uses: ejcsid/policy-as-code@0.0.1
        with:
          policy: ejcsid/test-github-actions
          policy-path: policies/default.yaml
          policy-branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
          argvs: "--display --disable-dependabot --disable-secret-scanning --disable-code-scanning"
          
