name: build and test

on: [push]

jobs:
  compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
    
      - name: Build with Maven
        run: mvn -B -Pgitlab-cicd verify -Dmaven.main.skip --file pom.xml

